const S={p:"n3_progress",m:"n3_mastery",w:"n3_wrong_answers",r:"n3_review_schedule",h:"n3_question_history",e:"n3_examiner_history",c:"n3_saved_cards"},get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let P=get(S.p,{ability:50,answered:0,correct:0,cat:{},concept:{},confusions:{}}),M=get(S.m,{}),W=get(S.w,{}),R=get(S.r,{}),H=get(S.h,[]),E=get(S.e,[]),C=get(S.c,{}),Q=[],mode="examiner",round=[],ri=0,cur=null,results=[],before=50;
const $=x=>document.querySelector(x),esc=x=>String(x).replace(/[&<>"']/g,a=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[a]));
function save(){Object.entries({[S.p]:P,[S.m]:M,[S.w]:W,[S.r]:R,[S.h]:H,[S.e]:E,[S.c]:C}).forEach(([k,v])=>put(k,v))}
function band(n){return n<40?"N4 基礎仍需鞏固":n<55?"N3 入門階段":n<70?"N3 基礎":n<80?"N3 中段":n<90?"N3 中後段":"N3 高熟練度"}
function view(id){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");scrollTo(0,0)}
function mastery(id){return M[id]??(M[id]={a:0,c:0,d:{辨認:.5,意思:.5,辨析:.5,語境:.5,主動使用:.2},s:"new"})}
function weakness(q){let m=M[q.id],c=P.concept[q.conceptGroup],v=.15;if(m)v+=(1-(m.d.辨析+m.d.語境+m.d.辨認)/3)*.5;if(c?.a)v+=(1-c.c/c.a)*.35;if(R[q.id]&&new Date(R[q.id])<=new Date())v+=.4;return v}
function choose(){let pool=Q.filter(q=>q.validity==="valid"),used=new Set(),out=[];let target=Math.max(1,Math.min(5,Math.round(P.ability/20)+1));while(out.length<10){let a=pool.filter(q=>!used.has(q.id));if(!a.length)break;if(mode==="review"){let d=a.filter(q=>R[q.id]&&new Date(R[q.id])<=new Date());if(d.length)a=d}a.sort((x,y)=>(weakness(y)-Math.abs(y.difficulty-target)*.15)-(weakness(x)-Math.abs(x.difficulty-target)*.15));let last=out.slice(-3).map(x=>x.category),q=a.find(q=>!(last.length===3&&last.every(c=>c===q.category)))||a[0];out.push(q);used.add(q.id)}return out}
function start(m){mode=m;round=choose();ri=0;results=[];before=P.ability;view("quiz");renderQ()}
function renderQ(){cur=round[ri];$("#counter").textContent=`第 ${ri+1} / ${round.length} 題`;$("#bar").style.width=(ri/round.length*100)+"%";$("#cat").textContent={grammar:"文法",vocabulary:"詞彙",kanji:"漢字",meaning:"語意",usage:"用法"}[cur.category];$("#diff").textContent=`難度 ${cur.difficulty}`;$("#question").textContent=cur.question;$("#feedback").innerHTML="";let es=Object.entries(cur.options).sort(()=>Math.random()-.5);$("#options").innerHTML=es.map(([k,v])=>`<button class="option" data-k="${k}"><b>${k}.</b> ${esc(v)}</button>`).join("");document.querySelectorAll(".option").forEach(b=>b.onclick=()=>answer(b.dataset.k));$("#why").onclick=why;$("#explain").onclick=other;$("#next").onclick=next}
function answer(k){if(results[ri])return;let ok=k===cur.answer;document.querySelectorAll(".option").forEach(b=>{b.disabled=true;if(b.dataset.k===cur.answer)b.classList.add("correct");if(b.dataset.k===k&&!ok)b.classList.add("wrong")});$("#feedback").className="feedback "+(ok?"good":"bad");$("#feedback").innerHTML=`<b>${ok?"✓ 正確！":"✕ 不正確"}</b><br>${ok?"答對了。":`你的答案：${k}。正確答案：${cur.answer}。`}`;record(ok,k)}
function record(ok,k){results[ri]={q:cur,ok,k};P.answered++;if(ok)P.correct++;P.cat[cur.category]??={a:0,c:0};P.cat[cur.category].a++;if(ok)P.cat[cur.category].c++;P.concept[cur.conceptGroup]??={a:0,c:0};P.concept[cur.conceptGroup].a++;if(ok)P.concept[cur.conceptGroup].c++;let m=mastery(cur.id);m.a++;if(ok)m.c++;Object.keys(m.d).forEach(x=>m.d[x]=Math.max(0,Math.min(1,m.d[x]+(ok?.1:-.14))));let avg=Object.values(m.d).reduce((a,b)=>a+b,0)/5;m.s=avg>.88&&m.a>=6?"mastered":avg>.68?"familiar":avg>.42?"unstable":"learning";let days={new:1,learning:3,unstable:2,familiar:7,mastered:21}[m.s],d=new Date();d.setDate(d.getDate()+days);R[cur.id]=d.toISOString();if(ok)delete W[cur.id];else W[cur.id]={error:errType(cur),at:new Date().toISOString()};P.ability=Math.max(0,Math.min(100,Math.round(P.ability+(ok?2.5+(cur.difficulty-3)*1.2:-3-(cur.difficulty-3)*.5))));H.unshift({id:cur.id,ok,k,time:new Date().toISOString(),category:cur.category});H=H.slice(0,300);save();home()}
function errType(q){if(q.category==="kanji")return"漢字讀音";if(q.category==="vocabulary")return"詞彙混淆";if(q.category==="meaning")return"意思理解";if(q.skill==="grammar_distinction")return"文法混淆";return"語境判斷"}
function why(){open("📖 為甚麼？",`<p>${esc(cur.explanation.correct)}</p><p><b>💡 記憶重點</b><br>${esc(cur.explanation.keyPoint)}</p><p>考點：${esc(cur.explanation.grammarPoint)}</p>`)}
function other(){open("🔍 其他選項",Object.entries(cur.options).map(([k,v])=>`<p><b>${k}. ${esc(v)}</b><br>${k===cur.answer?"✓ 正確":"✕ 不適合"}：${esc(cur.explanation.options[k])}</p>`).join(""))}
function open(t,b){$("#dtitle").textContent=t;$("#dbody").innerHTML=b;$("#dialog").showModal()}
function next(){if(!results[ri])return;if(ri<round.length-1){ri++;renderQ()}else finish()}
function finish(){let score=results.filter(x=>x.ok).length;E.unshift({time:new Date().toISOString(),score,before,after:P.ability});E=E.slice(0,50);save();$("#score").textContent=score+"/10";$("#summary").textContent=`本輪答對 ${score} 題。`;$("#before").textContent=before;$("#after").textContent=P.ability;$("#rg").textContent=fmt("grammar");$("#rv").textContent=fmt("vocabulary");$("#rk").textContent=fmt("kanji");let o=results.filter(x=>x.q.category==="meaning"||x.q.category==="usage");$("#ro").textContent=o.length?`${o.filter(x=>x.ok).length}/${o.length}`:"-";let bad=results.filter(x=>!x.ok);$("#obs").innerHTML=bad.length?`<p>• 本輪有 ${bad.length} 題錯誤；考官會增加相關弱點及相似概念複習權重。</p>`:"<p>• 本輪全部答對；下一輪會逐步提高難度。</p>";$("#conf").innerHTML=bad.map(x=>`<span class="chip orange">${errType(x.q)}</span>`).join("")||"暫未形成明顯混淆。";view("result")}
function fmt(c){let a=results.filter(x=>x.q.category===c);return a.length?`${a.filter(x=>x.ok).length}/${a.length}`:"-"}
function home(){let ms=Object.values(M),av=ms.length?Math.round(ms.reduce((s,m)=>s+Object.values(m.d).reduce((a,b)=>a+b,0)/5,0)/ms.length*100):0;$("#ability").textContent=P.ability;$("#band").textContent=band(P.ability);$("#mastery").textContent=av+"%";$("#wrong").textContent=Object.keys(W).length;$("#answered").textContent=P.answered;let w=Object.entries(P.concept).sort((a,b)=>(1-b[1].c/b[1].a)-(1-a[1].c/a[1].a)).slice(0,7);$("#homeWeak").innerHTML=w.length?w.map(([k,v])=>`<span class="chip ${v.c/v.a<.5?"red":"orange"}">${esc(k)} · ${Math.round((1-v.c/v.a)*100)}%</span>`).join(""):"暫未有足夠數據。"}
function progress(){home();$("#pa").textContent=P.ability;$("#pb").textContent=band(P.ability);$("#pc").textContent=P.correct;$("#pt").textContent=P.answered;$("#pm").textContent=$("#mastery").textContent;let w=Object.entries(P.concept).sort((a,b)=>(1-b[1].c/b[1].a)-(1-a[1].c/a[1].a));$("#weakmap").innerHTML=w.length?w.map(([k,v])=>`<div class="weakrow"><span>${esc(k)}</span><div class="meter"><i style="width:${Math.max(4,(1-v.c/v.a)*100)}%"></i></div><b>${Math.round((1-v.c/v.a)*100)}%</b></div>`).join(""):"暫無數據";$("#matrix").innerHTML=Object.entries(P.confusions).map(([k,v])=>`<span class="chip orange">${esc(k)} · ${v}</span>`).join("")||"答錯相似概念後會在此顯示。";let qmap=Object.fromEntries(Q.map(q=>[q.id,q]));$("#cards").innerHTML=Object.entries(M).filter(([,m])=>m.s==="familiar"||m.s==="mastered").slice(0,12).map(([id,m])=>`<div class="knowledge"><b>${esc(qmap[id]?.grammarPoint||id)}</b><br>熟練度：${Math.round(Object.values(m.d).reduce((a,b)=>a+b,0)/5*100)}%</div>`).join("")||"暫未形成知識卡";$("#hist").innerHTML=H.slice(0,10).map(x=>`<div class="history">${x.ok?"✓":"✕"} ${esc(x.id)} · ${new Date(x.time).toLocaleString("zh-HK",{hour12:false})}</div>`).join("")||"暫無紀錄"}
document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>start(b.dataset.mode));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>{view(b.dataset.go);if(b.dataset.go==="progress")progress()});$("#quit").onclick=()=>view("home");$("#again").onclick=()=>start(mode);$("#close").onclick=()=>$("#dialog").close();fetch("questions.json").then(r=>r.json()).then(x=>{Q=x;home()}).catch(()=>alert("題庫載入失敗，請確認 questions.json 與 index.html 在同一目錄。"));
